prueba_primer_homepage:
    path:     /Prueba
    defaults: { _controller:PruebaPrimerBundle:Default:index }

insertar_movimientos:
    path: /insertar-mov
    defaults: { _controller:PruebaPrimerBundle:Default:insertarMov}

get_movimientos:
    path: /movimientos
    defaults: { _controller:PruebaPrimerBundle:Default:getMovimientos}

get_saldo:
    path: /saldo
    defaults: { _controller:PruebaPrimerBundle:Default:getSaldo}